name: pedidos_app
description: App simple para gestionar pedidos (clientes, proveedores y materiales) y compartir por WhatsApp/Email.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_clientes.csv
    - assets/sample_proveedores.csv
    - assets/sample_materiales.csv
